version: '3.4'

services:
  web:
    build: .
    depends_on:
      - database
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
  database:
    image: postgres:13
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"